name = "deusdormit-modpack"
author = "deusdormit"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18bb47d9f045369343d90b9ad00f0cf2b8c3483679c005a06a2f60918e8d2afe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
