name = "deusdormit-modpack"
author = "deusdormit"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20b5309bdc2565de1a9b955ce9395226231c8b53265a84c1bcae46e736fbd481"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
