name = "deusdormit-modpack"
author = "deusdormit"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a9c6db2d71ec36da14fc3d9d4246de0d76b4c60058459c3d1827488fbcc45da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
